### ISSUE TITLE
Was it possible to add Swing Mode support?

### ISSUE THREAD

**Issue by Basicek1** [MiguelAngelLV/esphaier#10]
Was it possible to add Swing Mode support?

So far, I have used another modification of haier.h, which stopped working with the ESPHome upgrade to version 1.19.4.
Would anyone please advise me how to modify the code?

[Haier.txt](https://github.com/MiguelAngelLV/esphaier/files/6708113/Haier.txt)

Thank you very much for this project

**Comment by MiguelAngelLV** [comment]
Try to change CLIMATE_MODE_AUTO to CLIMATE_MODE_HEAT_COLD.

When I upgrade to 1.9.0, I got a "invalud value 6 mode" error. Maybe It is your case.

My AC don't have Swing mode (It is by conducts), so I can't test the swing mode...

**Comment by Basicek1** [comment]
I have a suggestion to modify the code for the new version of ESPHome 1.19.0. For my Haier air conditioner, this code also works. Please try it.

[Haier.txt](https://github.com/MiguelAngelLV/esphaier/files/6720715/Haier.txt)

**Comment by megachammer** [comment]
I've checked **Basicek1**'s version. Everything seems to work fine with 1.19.4, swing also.
Thanx!

**Comment by evlo** [comment]
> Was it possible to add Swing Mode support?
> 
> So far, I have used another modification of haier.h, which stopped working with the ESPHome upgrade to version 1.19.4. Would anyone please advise me how to modify the code?
> 
> [Haier.txt](https://github.com/MiguelAngelLV/esphaier/files/6708113/Haier.txt)
> 
> Thank you very much for this project



> Was it possible to add Swing Mode support?
> 
> So far, I have used another modification of haier.h, which stopped working with the ESPHome upgrade to version 1.19.4. Would anyone please advise me how to modify the code?
> 
> [Haier.txt](https://github.com/MiguelAngelLV/esphaier/files/6708113/Haier.txt)
> 
> Thank you very much for this project

did you get `LED_BIT_OFF` to work?
