### ISSUE TITLE
Could you add the silent mode?

### ISSUE THREAD

**Issue by megachammer** [MiguelAngelLV/esphaier#11]
It would be great if you add the silent mode. Right now it is possible to turn it on/off from IR remote, bun not from Home Assistant.
Thanx!

**Comment by MiguelAngelLV** [comment]
I need the buffer bytes with and without silent mode to find the byte of the mode.

**Comment by MiguelAngelLV** [comment]
I added "conforn mode", the unique mode in my AC, so, I can check other modes without buffers bytes comparations.
