### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by sir90ha** [MiguelAngelLV/esphaier#13]
Уважаемый автор Oksion имею hair, и на нем присутствует разъем ch35, как и у вас, но пытаясь настроить вифи узнал что в некоторых моделях этот разъем не работает,. Прошу вас сделать фотку или скан задней стороны платы (а именно дорожки и куда они ведут)

**Comment by MiguelAngelLV** [comment]
Sorry, I don't speak russian, so I have to translate with Google and I don't sure what you need..

A board connection photo?

In the readme have one:

![image](https://user-images.githubusercontent.com/638110/127106085-67a03413-00f4-4a38-928f-5b9e94ea956b.png)

**Comment by sir90ha** [comment]
no, I will ask you a photo of the air conditioner board itself, since in my model there is a jumper somewhere to disconnect the cn35 connector
________________________________

**Comment by sir90ha** [comment]
[Image]

[Image]

[Image]

[Image]


________________________________

**Comment by MiguelAngelLV** [comment]
I can't open the AC.  The connector of AC is a USB.

**Comment by sir90ha** [comment]
+5 and gnd work.
but rx tx do not work. I want to know where and how the tracks from these contacts go.
________________________________

**Comment by MiguelAngelLV** [comment]
Your images didn't upload correctly. Can you reupload from Github (not email) ?

**Comment by sir90ha** [comment]
https://drive.google.com/folderview?id=1YL_LBsUsehT_sPjDsYuicAz9xMyrxEUQ
________________________________

**Comment by sir90ha** [comment]
I am confused by the decoupling of the circuit (circled it)
________________________________

**Comment by MiguelAngelLV** [comment]
Ums... I haven't any idea...

Did you try interchange rx and rt?

**Comment by sir90ha** [comment]
Yes, I tried it, even directly via ttl usb to the PC.

in e same, I think that there is a jumper somewhere, so I ask for a photo of the board of my air conditioner
________________________________
