### ISSUE TITLE
Add support to change temperature

### ISSUE THREAD

**Issue by Chrismelba-Instaclustr** [MiguelAngelLV/esphaier#15]
I love this app, thank you so much for making it.

However when I try to make an automation through the GUI in homeassisstant I can only chnage the HVAC mode, not the temperature? Not sure why this would be, as I can see the temp in the list of states and change it via the lovelace card?

**Comment by MiguelAngelLV** [comment]
These is not problem of integration, is Home Assistant automation options. You must use **call service** action instead **device** action.

In call service, you have climate.set_temperature service to set the temperature that you want.
