### ISSUE TITLE
Temperature step 0.5 Celsius

### ISSUE THREAD

**Issue by OwlBawl** [MiguelAngelLV/esphaier#20]
Hi, thanks for your job.
Is it possible to modify command to 0.5 celsius target temperature step?
Homekit / Homeassistant and my aircon with wired remote - all supporting this step...
would appreciate for your help

**Comment by OwlBawl** [comment]
<img width="912" alt="Screenshot 2022-07-24 at 12 02 17" src="https://user-images.githubusercontent.com/7028077/180640085-4655237d-51fe-4df5-b84a-07b82661eef3.png">
tried to set .5 temperature with the remote and saved responses after 
- it seems that for .5 celsius the 29 raw is changing only to "41" when temperature with ".5"
And the 36 raw, but it is a checksum as i understand.

**Comment by MiguelAngelLV** [comment]
I upload a pending update with some features. 

The update solve these problem in my AC. Checkout in your.

**Comment by OwlBawl** [comment]
Thank you
Updated Haier.h + yaml with swing (false) - i really dont have swing on my in-ceiling model )
Results:
I can now set .5 temp via HA and Homekit
I can change the Fan speed + auto
I dont have "peset" and it seems changes nothing for me.

And the main now:
Can't turn on AC not via HA not Homekit (any mode: heat/cool, cool, heat)
But can turn off in both. Changing temp to int - doesn't help.

**Comment by MiguelAngelLV** [comment]
>I can now set .5 temp via HA and Homekit
 Great!


>Can't turn on AC not via HA not Homekit (any mode: heat/cool, cool, heat)

Um... Check the new update.

**Comment by OwlBawl** [comment]
Almost perfect now.
Just one bug mentioned - 
For example:
if you turned OFF in Heat mode
and turn on Heat/Cool - it resets on Heat mode and turn on. Then you need manually switch again to Heat/Cool

**Comment by OwlBawl** [comment]
This one your fork for newer models operates with turn on states correctly
[**](https://github.com/albetaCOM/esp-haier/blob/d5e9bd6dabcdd9c8f442dfb24d35b6bb29159292/Haierv2.h)

**Comment by MiguelAngelLV** [comment]
New update... Maybe now?

**Comment by OwlBawl** [comment]
> New update... Maybe now?

Now we got kinda loop.
When turn on mode - it turn on on instance and then switch to off immediately

**Comment by OwlBawl** [comment]
Just checked specially.
restored your previous Haier.h version on ESP - it was working as expected, no troubles with turn on state.

**Comment by MiguelAngelLV** [comment]
What version? Yesterday or one hour ago?

**Comment by OwlBawl** [comment]
Yesterday. Which didn't support 0.5 degrees

I'm just a diy hobbyist without coding abilities... )
But if I understand correctly: in your previous version and in [albetaCOM fork](https://github.com/albetaCOM/esp-haier/blob/d5e9bd6dabcdd9c8f442dfb24d35b6bb29159292/Haierv2.h)
turn On + State are sent simultaneously in one string, and now you've made separate string for turn on -> then mode

        if (call.get_mode().value() != esphome::climate::CLIMATE_MODE_OFF && (data[POWER] & POWER_MASK) == 0) {
            sendData(on, sizeof(on));
            delay(1000);
        }

**Comment by miguelangellv** [comment]
Ok, check again... I combine the yesterday method with 0.5 detection...

The main problem is that my AC works fine with all methods...

**Comment by OwlBawl** [comment]
You made it )
Many thanks to you !

**Comment by miguelangellv** [comment]
Thanks you for the testing ;)

**Comment by OwlBawl** [comment]
Just for interest - what's the "Comfort" preset?
i think i'll comment it for my case

**Comment by miguelangellv** [comment]
Some ACs have "special modes". My AC have a mode "quiet", but EspHome/HA don't have these mode so I use "Conform" as equivalent.

These are the Esphome modes:


```enum ClimatePreset : uint8_t {
  /// No preset is active
  CLIMATE_PRESET_NONE = 0,
  /// Device is in home preset
  CLIMATE_PRESET_HOME = 1,
  /// Device is in away preset
  CLIMATE_PRESET_AWAY = 2,
  /// Device is in boost preset
  CLIMATE_PRESET_BOOST = 3,
  /// Device is in comfort preset
  CLIMATE_PRESET_COMFORT = 4,
  /// Device is running an energy-saving preset
  CLIMATE_PRESET_ECO = 5,
  /// Device is prepared for sleep
  CLIMATE_PRESET_SLEEP = 6,
  /// Device is reacting to activity (e.g., movement sensors)
  CLIMATE_PRESET_ACTIVITY = 7,
};
```

The more similar is conform or, maybe, sleep, but some devices have sleep mode and quiet mode, so I use conform as quiet.

**Comment by OwlBawl** [comment]
Can you advice please how can i disable it for my instance?
Have no "extra" modes. to eliminate conflicts possible

**Comment by miguelangellv** [comment]
Comment / remove lines 173 and 174

https://github.com/MiguelAngelLV/esphaier/blob/master/Haier.h#L173

**Comment by OwlBawl** [comment]
Thank you!
