### ISSUE TITLE
Compiling error

### ISSUE THREAD

**Issue by krzakx** [MiguelAngelLV/esphaier#25]
Hello.
Unfortunately I got following error while compiling in ESPHome dashboard:
```
/config/esphome/haier.yaml: In lambda function:
/config/esphome/haier.yaml:34:24: error: expected type-specifier before 'Haier'
   34 |       auto haier = new Haier(swing);
      |                        ^~~~~
/config/esphome/haier.yaml:36:20: error: could not convert '{haier}' from '<brace-enclosed initializer list>' to 'std::vector<esphome::climate::Climate*>'
   36 |       return {haier};
      |                    ^
      |                    |
      |                    <brace-enclosed initializer list>
Compiling /data/haier/.pioenvs/haier/lib67b/ESP8266WiFi/ESP8266WiFiGeneric.cpp.o
Compiling /data/haier/.pioenvs/haier/lib67b/ESP8266WiFi/ESP8266WiFiGratuitous.cpp.o
*** [/data/haier/.pioenvs/haier/src/main.cpp.o] Error 1
```

Can you take look for solution please?

**Comment by miguelangellv** [comment]
Did you add the include Haier.h?

Look the line 5


https://github.com/MiguelAngelLV/esphaier/blob/master/esphaier.yaml#L5

**Comment by krzakx** [comment]
> Did you add the include Haier.h?
> 
> Look the line 5
> 
> 
> https://github.com/MiguelAngelLV/esphaier/blob/master/esphaier.yaml#L5

Thanks for your replay.
.h file was included in place.

An issue was about target compiling platform it has not success for web esphome flasher but work out for "Legacy format" and then I've used .exe stand alone flasher for burning.
Now it works, so far no issue.

Thank you for your contribution.

**Comment by miguelangellv** [comment]
Ok, perfect.
