### ISSUE TITLE
Flashing issue

### ISSUE THREAD

**Issue by priknr1** [MiguelAngelLV/esphaier#28]
Hi, 

Sorry if this is me being a noob, but I cant seem to flash the yaml file.
I dont have Home Assistent running, but in Homey (a competitor) there is an addon to work with ESPhome.

I am trying to upload the yaml with ESPHOME-flasher.
But I think I should have a step somewhere in between to create a firmware.bin from the YAML file?   I am searching for hours, but I am lost. Would you please be so kind to point me in the right direction?

**Comment by miguelangellv** [comment]
You need flash using esphome app, maybe Homey has only a "integration" but not a flasher. 

This tutorial show how install and flash without any addon, directly from your computer

https://esphome.io/guides/getting_started_command_line.html
