### ISSUE TITLE
esphome::climate::Climate::away' is deprecated: away is deprecated, use preset instead [-Wdeprecated-declarations]

### ISSUE THREAD

**Issue by OwlBawl** [MiguelAngelLV/esphaier#29]
Hi, I'm receiveing this yellow lines in console while updating ESP firmware, could you advice plese.

In file included from src/esphome/core/controller.h:29,
                 from src/esphome/components/api/api_server.h:4,
                 from src/esphome/components/api/api_connection.h:6,
                 from src/esphome.h:3,
                 from src/main.cpp:3:
src/esphome/components/climate/climate.h: In constructor 'esphome::climate::Climate::Climate()':
src/esphome/components/climate/climate.h:167:7: warning: 'esphome::climate::Climate::away' is deprecated: away is deprecated, use preset instead [-Wdeprecated-declarations]
  167 | class Climate : public EntityBase {
      |       ^~~~~~~
src/esphome/components/climate/climate.h:193:8: note: declared here
  193 |   bool away{false};
      |        ^~~~
src/esphome/components/climate/climate.h:167:7: warning: 'esphome::climate::Climate::away' is deprecated: away is deprecated, use preset instead [-Wdeprecated-declarations]
  167 | class Climate : public EntityBase {
      |       ^~~~~~~
src/esphome/components/climate/climate.h:193:8: note: declared here
  193 |   bool away{false};
      |        ^~~~
In file included from src/main.cpp:24:
src/HaierGuestroom.h: In constructor 'Haier::Haier(bool)':
src/HaierGuestroom.h:95:50: note: synthesized method 'esphome::climate::Climate::Climate()' first required here
   95 |     Haier(bool swing) : PollingComponent(5 * 1000) {
      |                                                  ^
src/HaierGuestroom.h: In member function 'virtual void Haier::control(const esphome::climate::ClimateCall&)':
src/HaierGuestroom.h:345:20: warning: enumeration value 'CLIMATE_FAN_QUIET' not handled in switch [-Wswitch]
  345 |             switch (call.get_fan_mode().value()) {
      |                    ^

**Comment by miguelangellv** [comment]
Hi!

Now you can use this component with official support of EspHome:

https://esphome.io/components/climate/haier.html

**Comment by OwlBawl** [comment]
Could you please advice how to change it in code 🥹
