### ISSUE TITLE
How to control central air conditioning with multiple indoor units

### ISSUE THREAD

**Issue by linrol** [MiguelAngelLV/esphaier#31]
Thanks for your project, I can already control my central air conditioner. How can I modify the yml file to control multiple indoor units?

**Comment by miguelangellv** [comment]
This version is not compatible.

Please, use the official version in Esphome(https://esphome.io/components/climate/haier.html ) and set multiples UARTS, one UART by unit.

**Comment by linrol** [comment]
OK, thanks for your guidance
