### ISSUE TITLE
No responding on AC

### ISSUE THREAD

**Issue by monteship** [MiguelAngelLV/esphaier#5]
climate.haier | off | hvac_modes: heat_cool, off, cool, heat min_temp: 10 max_temp: 50 target_temp_step: 1 current_temperature: null temperature: 0 friendly_name: Haier supported_features: 1
-- | -- | --

[23:34:23][D][Haier:105]: POLL: 
0-255
1-255
2-10
3-0
4-0
5-0
6-0
7-0
8-1
9-1
10-77
11-1
12-90 
[23:34:28][D][Haier:105]: POLL: 
0-255
1-255
2-10
3-0
4-0
5-0
6-0
7-0
8-1
9-1
10-77
11-1
12-90

**Comment by MiguelAngelLV** [comment]
It look like It don't  received all data from AC...

Maybe you can try the Albeta version, is for other firmware version, maybe works for you: https://github.com/albetaCOM/esphaier
