### ISSUE TITLE
current temperature

### ISSUE THREAD

**Issue by mcike59295** [MiguelAngelLV/esphaier#8]
Hello
everything works correctly except the current temperature in standby and function are not the same!

**Comment by eboboshka** [comment]
@mcike59295 I think that this is not a software error, because with the standard WIFI module Haier AC device shows the wrong temperature (On the display and in the Haier AC app).

**Comment by mcike59295** [comment]
OK thank you very much for the information 👍

**Comment by MiguelAngelLV** [comment]
Ups, sorry. for any reason, I don't receive alerts from the repository... 

Finally it worked?
