### ISSUE TITLE
Tuto ?

### ISSUE THREAD

**Issue by euhkah** [MiguelAngelLV/esphaier#9]
Hello,
Is it possible to do a tutorial ? with photos ? Because I don't know what a "Wemos D1 Mini" is... I would like to connect my HA with my AC Haier, but I feel like I have to be an engineer... The original module should be replaced by this mysterious Wemos ? I have an ESP32 module, I don't want to go through the Chinese cloud.

Thank you

**Comment by MiguelAngelLV** [comment]
Wemos D1 is a ESP8266 popular board, a previous version of ESP32. Is very cheap (4-5$).

Yes, you can reemplace the Haier module.


![image](https://user-images.githubusercontent.com/638110/122714696-03603300-d268-11eb-95e4-5b335c287d08.png)


You flash the Wemos D1, use a old USB cable and solder in the connections and... "voilá".

**Comment by euhkah** [comment]
Thank you ! 

I understood that it was necessary to install ESPHome, in supervisor, edit the yaml, copy the haier.h in the folder of ESPHome and install the firmware created with ESPHome...

It is surely obvious to you, it was not clear to me 😅 (I thought that was something to do with Arduino or ESP Easy ...!)

I passed all the steps, and the logs give me the right values ​​😎!  I can not yet create an entity, I think it from the new version of ESPHome ?  I find a device, but without an entity... !
"merci" 😉

**Comment by MiguelAngelLV** [comment]
Oh sorry, I thought you used esphome before.

Check if you have 1.9.2 version of EspHome. The 1.9.1 have a bug and Home Assistant don't show the entity.

**Comment by euhkah** [comment]
Yes !

PLATFORMIO_D1_MINI
par espressif
Firmware: 1.19.2 (Jun 21 2021, 18:57:20)

maybe something else

**Comment by MiguelAngelLV** [comment]
Find in the Home Assistant core logs. 

Maybe can get the error.

**Comment by euhkah** [comment]
ESPHome log:

`ERROR Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOMainLoop object at 0x7f90d0e160>>, <Future finished exception=WebSocketClosedError()>)
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/tornado/ioloop.py", line 741, in _run_callback
    ret = callback()
  File "/usr/local/lib/python3.7/dist-packages/tornado/ioloop.py", line 765, in _discard_future_result
    future.result()
  File "/usr/local/lib/python3.7/dist-packages/tornado/gen.py", line 775, in run
    yielded = self.gen.send(value)
  File "/opt/esphome/esphome/dashboard/dashboard.py", line 255, in _redirect_stdout
    self.write_message({"event": "line", "data": data})
  File "/usr/local/lib/python3.7/dist-packages/tornado/websocket.py", line 337, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError`

Home Assistant core log:

`2021-06-21 22:51:47 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/esphome/__init__.py", line 214, in on_login
entity_infos, services = await cli.list_entities_services()
File "/usr/local/lib/python3.8/site-packages/aioesphomeapi/client.py", line 137, in list_entities_services
entities.append(cls(**kwargs))
File "<attrs generated init aioesphomeapi.model.ClimateInfo>", line 9, in __init__
self.supported_modes = __attr_converter_supported_modes(supported_modes)
File "/usr/local/lib/python3.8/site-packages/aioesphomeapi/model.py", line 245, in _convert_climate_modes
return [ClimateMode(val) for val in value]
File "/usr/local/lib/python3.8/site-packages/aioesphomeapi/model.py", line 245, in <listcomp>
return [ClimateMode(val) for val in value]
File "/usr/local/lib/python3.8/enum.py", line 339, in __call__
return cls.__new__(cls, value)
File "/usr/local/lib/python3.8/enum.py", line 662, in __new__
raise ve_exc
ValueError: 6 is not a valid ClimateMode`

Does this ring a bell ? Me, I don't understand, except there are 2 different versions of python... 😒

**Comment by MiguelAngelLV** [comment]
Did you deleted your comment?

Anyway.

>2021-06-21 22:51:47 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/components/esphome/__init__.py", line 214, in on_login entity_infos, services = await cli.list_entities_services() File "/usr/local/lib/python3.8/site-packages/aioesphomeapi/client.py", line 137, in list_entities_services entities.append(cls(**kwargs)) File "<attrs generated init aioesphomeapi.model.ClimateInfo>", line 9, in __init__ self.supported_modes = __attr_converter_supported_modes(supported_modes) File "/usr/local/lib/python3.8/site-packages/aioesphomeapi/model.py", line 245, in _convert_climate_modes return [ClimateMode(val) for val in value] File "/usr/local/lib/python3.8/site-packages/aioesphomeapi/model.py", line 245, in <listcomp> return [ClimateMode(val) for val in value] File "/usr/local/lib/python3.8/enum.py", line 339, in __call__ return cls.__new__(cls, value) File "/usr/local/lib/python3.8/enum.py", line 662, in __new__ raise ve_exc ValueError: 6 is not a valid ClimateMode


The "value error 6" is the error I get with 1.9.1 of esphome.

Maybe you can try delete haier folder in the ESPHome config folder in Hassio and reflash.

**Comment by euhkah** [comment]
Yes i deleted the comment, because i realized i was trying with albetaCOM's haier.h.

His gives me values in the logs (not in lovelace). Your version of hair.h doesn't work with my air conditioning. I think I have a newer air conditioner (but I'm not sure, I don't know how to find the firmware version).
But I can't ask you to help me with his version.

Thank you for your help, I made a lot of progress, thanks to your availability.

**Comment by MiguelAngelLV** [comment]
Ok, no problem. 

With any news, please, notify me  if you think I can improve my version :)
